name: Run tests

on:
  push:
    branches:
      - "issue-**"
  pull_request:
    branches: 
      - "dev"

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        python-version: ["3.7"] #, "2.7"]

    steps:
      - name: Install xmllint
        run: |
          sudo apt install build-essential wget -y
          wget https://artiya4u.keybase.pub/TA-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
      - uses: actions/checkout@v2
      - name: Cache Conda
        uses: actions/cache@v1
        with:
          path: /usr/share/miniconda/envs/ta_scanner
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-
      - name: Setup Conda dependencies
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: ta_scanner
          environment-file: environment.yml
          python-version: "${{ matrix.python-version }}"
          auto-activate-base: false
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest
