name: Run tests

on:
  push:
    branches: [ dev, "issue-12/base"]
  pull_request:
    branches: [ dev ]

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        python-version: ["3.7"] #, "2.7"]
    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: goanpeca/setup-miniconda@v1
    #     with:
    #       auto-update-conda: true
    #       python-version: ${{ matrix.python-version }}
    #       environment-file: ../environment.yml
    #   # - name: Conda info
    #   #   shell: bash -l {0}
    #   #   run: conda list
    #   # - name: Run tests
    #   #   shell: bash -l {0}
    #   #   run: pytest

    steps:
      # - name: Setup Conda dependencies
      #   uses: goanpeca/setup-miniconda@v1
      #   with:
      #     activate-environment: lab
      #     environment-file: ../environment.yml
      #     python-version: 3.7
      #     auto-activate-base: false
      - name: Check out
        uses: actions/checkout@v2
      
      - name: get list of files
        run: ls

      # - name: Conda info
      #   shell: bash -l {0}  # activate the conda environment
      #   run: |
      #     conda info
      #     conda list