name: Run tests

on:
  push:
    branches: [ dev, "issue-12/base"]
  pull_request:
    branches: [ dev ]

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        python-version: ["3.7"] #, "2.7"]
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: ../environment.yml
      - name: Conda info
        shell: bash -l {0}
        run: conda list
      - name: Run tests
        shell: bash -l {0}
        run: pytest